---
- name: Remove legacy yum repo file if present
  ansible.builtin.yum_repository:
    file: cernvm.repo
    name: "{{ item }}"
    state: absent
  loop:
    - cernvm
    - cernvm-config

- name: Configure CernVM yum repositories
  ansible.builtin.yum_repository:
    file: cernvm
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
    gpgcheck: true
    enabled: true
    protect: true
  loop:
    - name: cernvm
      description: CernVM packages
      baseurl: http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$releasever/$basearch/
    - name: cernvm-config
      description: CernVM-FS extra config packages
      baseurl: http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-config/EL/$releasever/$basearch/
  when: item.name != 'cernvm-config' or ansible_distribution_major_version | int < 10

- name: Download CernVM GPG key
  ansible.builtin.get_url:
    url: https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM-2048
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
    owner: root
    group: root
    mode: "0644"

- name: Import CernVM GPG key into RPM
  ansible.builtin.rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM

- name: Install CernVM-FS packages and dependencies (yum)
  ansible.builtin.yum:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
