---
- name: Remove legacy yum repo file if present
  ansible.builtin.yum_repository:
    file: cernvm.repo
    name: "{{ item }}"
    state: absent
  loop:
    - cernvm
    - cernvm-config

- name: Download CernVM GPG key
  ansible.builtin.get_url:
    url: "{{ cernvm_key_url }}"
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
    owner: root
    group: root
    mode: "0644"
    force: true
  vars:
    cernvm_key_url: >-
      {{
        'https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM-2048'
        if ansible_distribution_major_version | int >= 10
        else 'https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM'
      }}

- name: Configure CernVM repo
  ansible.builtin.yum_repository:
    file: cernvm
    name: cernvm
    description: CernVM packages
    baseurl: http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$releasever/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
    gpgcheck: true
    enabled: true
    protect: true

- name: Install CernVM-FS packages and dependencies (yum)
  ansible.builtin.yum:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
