---
- name: Install apt dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Install CernVM apt key
  ansible.builtin.get_url:
    url: "{{ cvmfs_apt_repository_key }}"
    dest: /etc/apt/keyrings/cernvm.gpg
    mode: '0644'

- name: Configure CernVM apt repository
  ansible.builtin.apt_repository:
    filename: cernvm.list
    mode: '0644'
    repo: "{{ cvmfs_apt_repository }}"

- name: Install CernVM-FS packages and dependencies (apt)
  ansible.builtin.apt:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
