---

- name: Make CernVM-FS key directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ cvmfs_keys | map(attribute='path') | map('dirname') | unique }}"

- name: Install CernVM-FS keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: root
    mode: 0444
  loop: "{{ cvmfs_keys }}"
  loop_control:
    label: "{{ item.path }}"
